[build]
  command = "npm run build"
  publish = "dist/public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  VITE_FIREBASE_API_KEY = "AIzaSyAXggS45GgtQEDKt7ylTmKMXIg2PPfmCB4"
  VITE_FIREBASE_AUTH_DOMAIN = "flute-notes-f985e.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "flute-notes-f985e"
  VITE_FIREBASE_DATABASE_URL = "https://flute-notes-f985e-default-rtdb.firebaseio.com"
  VITE_FIREBASE_STORAGE_BUCKET = "flute-notes-f985e.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "461328034114"
  VITE_FIREBASE_APP_ID = "1:461328034114:web:6bc32ef02899cd0932c0db"
  VITE_FIREBASE_MEASUREMENT_ID = "G-NCP8XDCGBD"
